revoltek/losoto

tools/H5parm_importer.py
I modified H5parm_importer.py to be able to load the names of the input filed from configuration files. It should work with the global db as usual but also accept now a json of a pckl file containing a dictionary with the names of the files.
The creation of the H5parm is separated in a function that gets the file names. The parsing of the options is practically the same but, if the globaldb name ends with "json" or "pckl" it will load the info from these type of files.
In general this allows to generalize a bit the load of the information. It has proven to be very useful in "non-standard" systems like mine.
Please, check that it still works with globaldb files as intended (It should but...).
=> Load information from files

losoto/operations/plot.py
Fixed a copy&paste error. IMHO this is obvious.
=> Bugfix for plot-prefixes with no directory component

bin/losoto, losoto/h5parm.py
Currently the check for being H5parm only checks whether the file is a pytables file. That is the wrong check: other software could write H5parm files, and pytables files exist that are not H5parm. This should fix this. Tested on example.h5 , and on the H5parm files the DPPP-prototype writes.
Also, somewhere `VERSION_H5PARM` is written instead of `h5parm_version`. I assumed there's no logic behind that, and changed it.
=> Better check for being H5parm, minor fixes

bin/H5parm_exporter.py
Very minor change to make sure reps argument for numpy.tile are integers rather than floats.
Fixes issue #17 and makes the script compatible for numpy >= 1.12.0.
Tested on 1.12.0 and 1.11.0 and is fine for numpy v1.9.0.
Note that other uses of np.tile may crash with >=1.12.0 versions of numpy (e.g. in losoto/operations/fitClockTEC.py) if the second argument is not, or contains, integers.
=> Fixes H5parm_exporter.py for numpy 1.12.0

bin/H5parm_exporter.py, losoto/h5parm.py, losoto/lib_unwrap.py, losoto/operations/example.py, losoto/operations/faraday.py, losoto/operations/plot.py, losoto/operations/prefactor_XYoffset.py, losoto/operations/tec.py
Here are a couple of minor fixes which makes the h5parm bit work on python3. Not sure if all losoto works; there are no tests...
The biggest change is how strings are handled. In python3, tables returns arrays of bytes rather than strings. I changed this to strings.
The changes should be backward compatible with python 2.
=> Some changes for python3

losoto/h5parm.py
in python 2.7 range is not a class, so only allow instance checking against slice for posterity
=> remove the selection checking against range for 2.7 compatibility

bin/killMS2H5parm.py
This adds an option to export just the XX and YY correlations, so they can be applied normally, i.e. not as `fulljones`, which gives me a bit of trouble at the moment when adding placeholder 1 (amp) or 0 (phase) solutions for the international staions.
It still exports fulljones by default, so this won't affect current functionality.
=> Add a flag to export just XX,YY from killMS solutions.

losoto/operations/__init__.py
Current losoto version won't work with Python 3.8. This commit fixes this.
=> Remove deprecated call to time.clock()

losoto/_version.py, setup.py
Loosened the version requirements on `scipy` and `matplotlib`, which were too stringent. Bumped version number to `2.2.1`.
=> Fix requirements

bin/losoto, losoto/operations/frjump.py
Implemented a relatively straight-forward rotation measure dejumper (FRjump). This is implemented as a separate operation so it won't interfere with already established pipelines. Limited testing shows promising results, but I haven't tried it on relatively 'bad' data (maybe I need to build in some sort of warning if the noise on the fitted rotation measure is too large (~0.5*jump size). I calculate the jump in a similar way to TECjump.
I made this change before, but now I did a bit more testing - I also cleaned up the code a bit (no longer dependent on astropy, for example), and I include a warning when using the FRjump module (that it is still experimental)
=> Implemented FRjump

losoto/operations/flagstation.py
Minor change. Don't let a `ValueError` sneak through in `flagstation.py:335`, because it will cause the thread to terminate and the main process to hang.
=> Fix uncaught exception in flagstation

losoto/operations/_faraday_timestep.py, losoto/operations/faraday.py
Basically, in "faraday.py" there is an if statement that checks the soltabtype. If soltabtype==phase all went well, but if soltabtype==rotation it didn't define coord_RR/LL. coordRR/LL is not needed for rotation tables, so these are set to None (_faraday_timestep doesn't use it either if the table is a rotation table). This works with the h5 you gave me.
=> Fixed bug with rotation table not being used in faraday fitting (also a typo is untypod)

losoto/operations/interpolate.py
This should fix #135. I managed to dig up a NumPy warning that slices should be tuples in newer versions from an older run:
```python
FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
```
Now it crashes instead of just warning. This fixes it for the interpolate option (as far as I have used it in LINC with an HBA calibrator scan) by casting the slice to a tuple. A small test ran seems to have run fine and I'm now running a full calibrator scan through to confirm.
**[Edit]**
Found the relevant release note: https://numpy.org/devdocs/release/1.23.0-notes.html
> …
=> Fix issue 135

losoto/operations/_fitClockTEC.py, losoto/operations/clocktec.py, losoto/operations/frjump.py, losoto/operations/plot.py, losoto/operations/tecjump.py
The using of `numpy.float` will throw an error in the most recent numpy release and just needs to be replaced.
References:
https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
=> np.float is deprecated in numpy==1.24.0

losoto/operations/flagstation.py
This PR fixes issue #141 by replacing the old `numpy.warnings` library with the `warnings` one.
=> Switch from numpy.warnings to warnings

losoto/h5parm.py
An `h5parm` object can now also be used in a `with` context. To retain backward compatibility, the underlying HDF5 file object is still opened in the `__init__()` method, but is now closed in the `__exit__()` method, which is implicitly called when leaving the `with` context.
Existing code will continue to function as it used to. You still need to call `close()` explicitly to close the HDF5 file object. New code should preferably use the `h5parm` object only inside a `with` context, thus ensuring that the HDF5 file object will always be closed, even when an exception is raised and not caught.
=> Add context support for h5parm class

bin/H5parm_collector.py, losoto/_importer.py, losoto/h5parm.py, losoto/operations/clocktec.py, losoto/operations/frjump.py, losoto/operations/prefactor_XYoffset.py, losoto/operations/tecjump.py, tools/swap_freq_time_axes.py
The use of float16 causes issues with, for example, NumPy's linalg routines. This PR removes instances where float16 is used and repaces them with float.
Fixes #142.
=> Remove use of float16 dtypes

setup.py, vagrant/bootstrap.sh
Hello @revoltek,
I hope you're doing well! I've just opened this pull request that proposes the removal of the unused `numexpr` dependency from the `setup.py` configuration file. It's part of an ongoing research endeavor focusing on the identification and elimination of code bloat within software projects. Your insights on this would be really valuable.
The `numexpr` library was introduced  in f63a515. However, an examination of the current codebase revealed that it is not used within the project. Removing this unused dependency can reduce the overall footprint of the application, mitigate potential security risks, and simplify the dependency management process.
- Removed the `numexpr`  dependency from the `setup.py` file.
- Updated `vagrant/bootstrap.sh` to reflect on the changes
- …
=> Remove Unused Dependency: Numexpr

losoto/operations/_faraday_timestep.py, losoto/operations/_fitClockTEC.py
The RM range [-0.1,0.1] in the faraday brutforce step is too small to handle IS data. Also, the tec operation sometimes crashed due to non-flagged NaNs.
=> faraday and tec fixes

.github/workflows/python.yml, losoto/operations/directionscreen.py, losoto/operations/stationscreen.py, setup.py
The `pinv()` function deprecated the use of `rcond` in favour of `rtol`, and SciPy 1.14.0 removed the keyword option `rcond` completely from `pinv()`. Replaced all occurrences of `rcond` in calls to `pinv()` with `rtol`.
=> Replace rcond with rtol in pinv() call

losoto/lib_operations.py, losoto/operations/faraday.py, losoto/operations/interpolatedirections.py, losoto/operations/prefactor_bandpass.py, losoto/operations/tec.py
Created a new function `nproc()` in `operations_lib.py`, which returns the number of CPU cores available to the current process, similar to what the Linux `nproc` command does. This can be less than the total number of CPU cores in the machine, which is returned by, e.g., `multiprocessing.cpu_count()`. Replaced calls to `multiprocessing.cpu_count()` with `nproc()`.
=>  Use number of available CPUs instead of total number 

losoto/operations/flagstation.py
This PR fixes an issue in the `flagstation` operation, where the original flags were not being restored properly when the flagged fraction is below `minFlaggedFraction`.
=> Fix restoration of original flags in flagstation

losoto/lib_operations.py
The function `nproc()` uses `os.sched_getaffinity()`, which is not available on every OS. It now uses `multiprocessing.cpu_count()` as fall-back.
=> Fix issue with function nproc
